server.port=8080
spring.data.mongodb.uri=mongodb://localhost:27017/studentdb
spring.data.mongodb.database=studentdb
event.service.url=http://localhost:8082
jwt.secret=thisisaverylongsecretkeythatisatleast32chars
jwt.expiration=86400000